name: AutoRelease

on:
  push:
    branches:
      - main  # Adjust to your release branch

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Set Version Date
        id: set_version
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=v$VERSION" >> $GITHUB_ENV

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.TAG }}
          prerelease: true
          title: "Release ${{ env.VERSION }}"
          files: |
            ./myfs  # Replace with the actual paths to the files you want to include in the release
