name: AutoRelease

on:
  push:
    branches:
      - main  # Adjust to your release branch

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}  # Use PAT instead of default GITHUB_TOKEN
          automatic_release_tag: "v${{ github.run_number }}" # You can customize this
          prerelease: true
          title: "Development Build"
          files: |
            ./myfs  # Replace with the actual paths to the files you want to include in the release
