name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build script
      run: ./build.sh

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Create release
      id: create_release
      run: |
        RELEASE_NAME="v$(date +'%Y%m%d%H%M%S')"
        gh release create $RELEASE_NAME ./myfs

    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./myfs
        asset_name: myfs
        asset_content_type: application/octet-stream
