name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build script
      run: ./build.sh

    - name: Set Version to Todays Date
      id: extract_version
      run: |
        VERSION=$(date +'%Y.%m.%d')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create and Upload Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        body: "Release of version ${{ env.VERSION }}"
        files: ./myfs
        prerelease: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
