name: AutoRelease

on:
  push:
    branches:
      - main  # Adjust this to the branch you use for releases

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Test
        run: |
          # Replace with your build and test commands
          echo "done!"

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            myfs  # Adjust to the files you want to include in the release
